# Generated by Django 3.1.12 on 2025-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sen', models.CharField(max_length=100, null=True)),
                ('rec', models.CharField(max_length=100, null=True)),
                ('mess', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('uname', models.CharField(max_length=100, null=True)),
                ('pas', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
